[package]
name = "aufgabe_4"
version = "0.1.0"
authors = ["Daniel <dada1016@hs-karlsruhe.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
